export enum BadgeType {
  DOCKER = "Docker",
  TYPESCRIPT = "TypeScript",
  EXPRESS = "ExpressJS",
  GIT = "Git",
  JAVASCRIPT = "JavaScript",
  TYPEORM = "TypeORM",
  FIREBASE = "Firebase",
  HTML = "HTML",
  REACT = "ReactJS",
  NODEJS = "NodeJS",
  CSS = "CSS",
  NEXTJS = "NextJS",
  POSTGRESQL = "PostgreSQL",
  SASS = "SASS",
  ANGULARJS = "AngularJS",
  MYSQL = "MySQL",
  JAVA = "Java",
  UNITY = "Unity",
  CSHARP = "Csharp",
  CPP = "Cpp",
  PYTHON = "Python",
}